name: duckbuck
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  firebase_auth: ^5.5.3
  liquid_swipe: ^3.1.0
  flutter_animate: ^4.5.2
  package_info_plus: ^8.3.0 
  image_picker: ^1.1.2
  provider: ^6.1.5
  url_launcher: ^6.3.1
  cloud_firestore: ^5.6.7
  slide_to_act: ^2.0.2
  firebase_analytics: ^11.4.5
  firebase_storage: ^12.4.5
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  firebase_app_check: ^0.3.2+5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.2.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  crypto: ^3.0.6
  lottie: ^3.3.1
  logger: ^2.5.0
  country_code_picker: ^3.3.0
  pin_code_fields: ^8.0.1
  pinput: ^5.0.1
  sms_autofill: ^2.4.1
  dio: ^5.8.0+1
  google_nav_bar: ^5.0.7
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - lib/core/legal/
