name: duckbuck
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  cloud_firestore: ^5.6.2
  flutter_svg: ^2.0.17
  provider: ^6.1.2
  url_launcher: ^6.3.1
  haptic_feedback: ^0.5.1+1
  vibration: ^3.1.1
  flutter_animate: ^4.5.2 
  animate_do: ^3.3.4
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.1
  permission_handler: ^11.3.1 
  package_info_plus: ^8.2.0
  image_cropper: ^9.0.0
  file_picker: ^8.3.1
  lottie: ^3.3.1
  agora_rtc_engine: ^6.5.0
  dio: ^5.8.0+1 
  record: ^5.2.0
  firebase_database: ^11.3.2
  just_audio: ^0.9.46
  audio_waveforms: ^1.2.0
  flutter_slidable: ^4.0.0 
  intl: ^0.20.2
  connectivity_plus: ^6.1.2 
  path_provider: ^2.1.5 
  shimmer: ^3.0.0
  mobile_scanner: ^6.0.6
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.4.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/apple.svg
    - assets/google.svg
    - assets/background.png
    - assets/riv/notifications.riv
    - assets/riv/switcher.riv
    - assets/riv/toggle_buttom.riv
    - assets/riv/dagger_death.riv
    - assets/app_icon.png
    - assets/loading.json
    - assets/success.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon.png"
  adaptive_icon_background: "#000000"
