// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbOjd1FX25Zbems5so9Vq8dEyYtd_BnA4',
    appId: '1:297951233838:web:28acc36ad12777f4581cbf',
    messagingSenderId: '297951233838',
    projectId: 'duckbuck-a2943',
    authDomain: 'duckbuck-a2943.firebaseapp.com',
    databaseURL: 'https://duckbuck-a2943-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'duckbuck-a2943.firebasestorage.app',
    measurementId: 'G-Z94PD17M8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
<<<<<<< Updated upstream
    apiKey: 'AIzaSyDF0O59dLvsX7cRqmd_JSTI6axn69GojMc',
    appId: '1:297951233838:android:b0eb75c32afb1e32581cbf',
    messagingSenderId: '297951233838',
    projectId: 'duckbuck-a2943',
    databaseURL: 'https://duckbuck-a2943-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'duckbuck-a2943.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg3SUEk3QYYV-8u_dQBuAHBggZ0ED6e9c',
    appId: '1:297951233838:ios:5b82861a21ff5e22581cbf',
    messagingSenderId: '297951233838',
    projectId: 'duckbuck-a2943',
    databaseURL: 'https://duckbuck-a2943-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'duckbuck-a2943.firebasestorage.app',
    androidClientId: '297951233838-00qlqepo7vjr74is2ksojetmvo557ptq.apps.googleusercontent.com',
    iosClientId: '297951233838-s63repuurh8rf12f4jkbleq7ipied51h.apps.googleusercontent.com',
    iosBundleId: 'com.example.duckbuck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg3SUEk3QYYV-8u_dQBuAHBggZ0ED6e9c',
    appId: '1:297951233838:ios:5b82861a21ff5e22581cbf',
    messagingSenderId: '297951233838',
    projectId: 'duckbuck-a2943',
    databaseURL: 'https://duckbuck-a2943-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'duckbuck-a2943.firebasestorage.app',
    androidClientId: '297951233838-00qlqepo7vjr74is2ksojetmvo557ptq.apps.googleusercontent.com',
    iosClientId: '297951233838-s63repuurh8rf12f4jkbleq7ipied51h.apps.googleusercontent.com',
    iosBundleId: 'com.example.duckbuck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbOjd1FX25Zbems5so9Vq8dEyYtd_BnA4',
    appId: '1:297951233838:web:6e9681a6529f3035581cbf',
    messagingSenderId: '297951233838',
    projectId: 'duckbuck-a2943',
    authDomain: 'duckbuck-a2943.firebaseapp.com',
    databaseURL: 'https://duckbuck-a2943-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'duckbuck-a2943.firebasestorage.app',
    measurementId: 'G-Q44RKB8K6F',
  );

=======
    apiKey: 'AIzaSyAEiTysCNzhhclVl9sLfG296GRlkD2wXwk',
    appId: '1:917171712740:android:1fa676a09409f91283f2f1',
    messagingSenderId: '917171712740',
    projectId: 'duckbuck-studios-test',
    storageBucket: 'duckbuck-studios-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxJ87DZNDm67kb_a6wJvGkann5BqpGNY',
    appId: '1:917171712740:ios:30b757acf5e78ccf83f2f1',
    messagingSenderId: '917171712740',
    projectId: 'duckbuck-studios-test',
    storageBucket: 'duckbuck-studios-test.firebasestorage.app',
    androidClientId: '917171712740-qkh4qg27ticfduvr3gilgaui6qrmmmua.apps.googleusercontent.com',
    iosClientId: '917171712740-cook3clnuhfkf62jsfphsf2uk3idkqq5.apps.googleusercontent.com',
    iosBundleId: 'com.duckbuck.app',
  );

>>>>>>> Stashed changes
}