// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAynrVfr8JRrWtEz2Y2uGDSPH68eFuOtXY',
    appId: '1:145652846516:web:61e0c0b32d2f5f01e56ce1',
    messagingSenderId: '145652846516',
    projectId: 'duckbuck-0',
    authDomain: 'duckbuck-0.firebaseapp.com',
    databaseURL: 'https://duckbuck-0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'duckbuck-0.firebasestorage.app',
    measurementId: 'G-0SR7LNRKGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmtKQo0sSCqNO5SMIIbGrEw0-GetPiVqI',
    appId: '1:145652846516:android:f4bb79873f602d51e56ce1',
    messagingSenderId: '145652846516',
    projectId: 'duckbuck-0',
    databaseURL: 'https://duckbuck-0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'duckbuck-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtOpORYFuzZjMvsCWePwh_OBNmp0bnbRI',
    appId: '1:145652846516:ios:8f7b5a8451b0800ce56ce1',
    messagingSenderId: '145652846516',
    projectId: 'duckbuck-0',
    databaseURL: 'https://duckbuck-0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'duckbuck-0.firebasestorage.app',
    iosClientId: '145652846516-s53os650719eoosf37ae97nouktiuu9e.apps.googleusercontent.com',
    iosBundleId: 'in.duckbuck.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtOpORYFuzZjMvsCWePwh_OBNmp0bnbRI',
    appId: '1:145652846516:ios:e167666c316a3205e56ce1',
    messagingSenderId: '145652846516',
    projectId: 'duckbuck-0',
    databaseURL: 'https://duckbuck-0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'duckbuck-0.firebasestorage.app',
    iosClientId: '145652846516-m60hvb1n45na08p2per36ck1n8s4jo1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.duckbuck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAynrVfr8JRrWtEz2Y2uGDSPH68eFuOtXY',
    appId: '1:145652846516:web:61e0c0b32d2f5f01e56ce1',
    messagingSenderId: '145652846516',
    projectId: 'duckbuck-0',
    authDomain: 'duckbuck-0.firebaseapp.com',
    databaseURL: 'https://duckbuck-0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'duckbuck-0.firebasestorage.app',
    measurementId: 'G-0SR7LNRKGD',
  );
}
